// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRating.API;

namespace MovieRating.API.Migrations
{
    [DbContext(typeof(MovieRatingDBContext))]
    partial class MovieRatingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieRating.API.Database.Actors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1987, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Meryl",
                            Gender = "Female",
                            LastName = "Streep"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1982, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Margot",
                            Gender = "Female",
                            LastName = "Robbie"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1999, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lupita",
                            Gender = "Female",
                            LastName = "Nyong'o"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johnny",
                            Gender = "Male",
                            LastName = "Depp"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1994, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            Gender = "Male",
                            LastName = "De Niro"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1992, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Al",
                            Gender = "Male",
                            LastName = "Pacino"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1980, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            Gender = "Male",
                            LastName = "Spacey"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1964, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Denzel",
                            Gender = "Male",
                            LastName = "Washington"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(2009, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Angelina",
                            Gender = "Female",
                            LastName = "Jolie"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1961, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Cruise"
                        });
                });

            modelBuilder.Entity("MovieRating.API.Database.ActorsMovies", b =>
                {
                    b.Property<int>("Actor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Movie_Id")
                        .HasColumnType("int");

                    b.HasKey("Actor_Id", "Movie_Id");

                    b.HasIndex("Movie_Id");

                    b.ToTable("ActorsMovies");

                    b.HasData(
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 1
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 1
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 2
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 2
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 3
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 3
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 4
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 4
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 5
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 5
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 6
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 6
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 7
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 7
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 8
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 8
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 9
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 9
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 10
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 10
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 11
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 11
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 12
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 12
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 13
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 13
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 14
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 14
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 15
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 15
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 16
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 16
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 17
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 17
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 18
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 18
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 19
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 19
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 20
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 20
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 21
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 21
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 22
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 22
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 23
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 23
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 24
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 24
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 25
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 25
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 26
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 26
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 27
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 27
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 28
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 28
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 29
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 29
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 30
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 30
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 31
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 31
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 32
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 32
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 33
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 33
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 34
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 34
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 35
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 35
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 36
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 36
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 37
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 37
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 38
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 38
                        },
                        new
                        {
                            Actor_Id = 3,
                            Movie_Id = 39
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 39
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 40
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 40
                        },
                        new
                        {
                            Actor_Id = 1,
                            Movie_Id = 41
                        },
                        new
                        {
                            Actor_Id = 8,
                            Movie_Id = 41
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 42
                        },
                        new
                        {
                            Actor_Id = 7,
                            Movie_Id = 42
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 43
                        },
                        new
                        {
                            Actor_Id = 5,
                            Movie_Id = 43
                        },
                        new
                        {
                            Actor_Id = 4,
                            Movie_Id = 44
                        },
                        new
                        {
                            Actor_Id = 9,
                            Movie_Id = 44
                        },
                        new
                        {
                            Actor_Id = 6,
                            Movie_Id = 45
                        },
                        new
                        {
                            Actor_Id = 2,
                            Movie_Id = 45
                        });
                });

            modelBuilder.Entity("MovieRating.API.Database.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RelaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeMovie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "http://image.tmdb.org/t/p/w185/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
                            Description = "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
                            RelaseDate = new DateTime(2020, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Guy (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dqoshZPLNsXlC1qtz5n34raUyrE.jpg",
                            Description = "A sequel to the horror film Candyman (1992) that returns to the now-gentrified Chicago neighborhood where the legend began.",
                            RelaseDate = new DateTime(2004, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Candyman",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "http://image.tmdb.org/t/p/w185/cGLL4SY6jFjjUZkz2eFxgtCtGgK.jpg",
                            Description = "A vacationing family discovers that the secluded beach where they're relaxing for a few hours is somehow causing them to age rapidly, reducing their entire lives into a single day.",
                            RelaseDate = new DateTime(2006, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Old",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "http://image.tmdb.org/t/p/w185/1N5e56325vwih8IeJ29k9FZf8p8.jpg",
                            Description = "Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities.",
                            RelaseDate = new DateTime(2012, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Malignant (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 5,
                            CoverImage = "http://image.tmdb.org/t/p/w185/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
                            Description = "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
                            RelaseDate = new DateTime(2007, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Suicide Squad (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 6,
                            CoverImage = "http://image.tmdb.org/t/p/w185/9424zyRdWp3Ze5XHsXZd64FeFGY.jpg",
                            Description = "A notorious criminal must break an evil curse in order to rescue an abducted girl who has mysteriously disappeared.",
                            RelaseDate = new DateTime(2006, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prisoners of the Ghostland (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 7,
                            CoverImage = "http://image.tmdb.org/t/p/w185/ysJte1iqN8pFQ470tumnViB1wHP.jpg",
                            Description = "Follows Alex, a boy obsessed with scary stories who is imprisoned by an evil young witch in her contemporary New York City apartment.",
                            RelaseDate = new DateTime(2002, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nightbooks",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 8,
                            CoverImage = "http://image.tmdb.org/t/p/w185/jGYJyPzVgrVV2bgClI9uvEZgVLE.jpg",
                            Description = "Six people unwittingly find themselves locked in another series of escape rooms, slowly uncovering what they have in common to survive. Joining forces with two of the original survivors, they soon discover they've all played the game before.",
                            RelaseDate = new DateTime(2000, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Escape Room: Tournament of Champions (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 9,
                            CoverImage = "http://image.tmdb.org/t/p/w185/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
                            Description = "A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.",
                            RelaseDate = new DateTime(2004, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Widow (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 10,
                            CoverImage = "http://image.tmdb.org/t/p/w185/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
                            Description = "Dom and the crew must take on an international terrorist who turns out to be Dom and Mia's estranged brother.",
                            RelaseDate = new DateTime(2009, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "F9: The Fast Saga",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 11,
                            CoverImage = "http://image.tmdb.org/t/p/w185/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg",
                            Description = "The sequel is set in the years following the initial deadly home invasion, where Norman Nordstrom (Stephen Lang) lives in quiet solace until his past sins catch up to him.",
                            RelaseDate = new DateTime(2010, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Don't Breathe 2 (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 12,
                            CoverImage = "http://image.tmdb.org/t/p/w185/cPdmPwcIcmu0ugfKcdFtI3vmOJq.jpg",
                            Description = "A father travels from Oklahoma to France to help his estranged daughter, who is in prison for a murder she claims she didn't commit.",
                            RelaseDate = new DateTime(2011, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stillwater (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 13,
                            CoverImage = "http://image.tmdb.org/t/p/w185/lB068qa6bQ0QKYKyC2xnYGvYjl7.jpg",
                            Description = "All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end.",
                            RelaseDate = new DateTime(2004, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Forever Purge (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 14,
                            CoverImage = "http://image.tmdb.org/t/p/w185/34BmdJkdvRweC3xJJFlOFQ2IbYc.jpg",
                            Description = "A group of criminals are brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways.",
                            RelaseDate = new DateTime(2001, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "No Sudden Move (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 15,
                            CoverImage = "http://image.tmdb.org/t/p/w185/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
                            Description = "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
                            RelaseDate = new DateTime(2002, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nobody",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 16,
                            CoverImage = "http://image.tmdb.org/t/p/w185/tbTiSr0v9g8Q34MIeIcT0o2vGus.jpg",
                            Description = "A mind-bending love story following Greg who, after recently being divorced and then fired, meets the mysterious Isabel, a woman living on the streets and convinced that the polluted, broken world around them is a computer simulation.",
                            RelaseDate = new DateTime(2005, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bliss (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 17,
                            CoverImage = "http://image.tmdb.org/t/p/w185/dPOyYnCkRbWAEem85N3VFpQODf5.jpg",
                            Description = "After being recruited by a group of unconventional thieves, renowned criminal Richard Pace finds himself caught up in an elaborate gold heist that promises to have far-reaching implications on his life and the lives of countless others.",
                            RelaseDate = new DateTime(2019, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Misfits",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 18,
                            CoverImage = "http://image.tmdb.org/t/p/w185/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg",
                            Description = "A G.I. Joe spin-off centered around the character of Snake Eyes.",
                            RelaseDate = new DateTime(2009, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Snake Eyes",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 19,
                            CoverImage = "http://image.tmdb.org/t/p/w185/wxLUQ1pIms3HAlVGYvEG9zg2kDs.jpg",
                            Description = "Jack Reacher must uncover the truth behind a major government conspiracy in order to clear his name. On the run as a fugitive from the law, Reacher uncovers a potential secret from his past that could change his life forever.",
                            RelaseDate = new DateTime(2017, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jack Reacher: Never Go Back",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 20,
                            CoverImage = "http://image.tmdb.org/t/p/w185/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
                            Description = "Based on Disneyland's theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.",
                            RelaseDate = new DateTime(2009, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jungle Cruise",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 21,
                            CoverImage = "http://image.tmdb.org/t/p/w185/faJK0dP3S92kQoKtO4LZMjy41kf.jpg",
                            Description = "In a twisted social experiment, 80 Americans are locked in their high-rise corporate office in Bogot�, Colombia and ordered by an unknown voice coming from the company's intercom system to participate in a deadly game of kill or be killed.",
                            RelaseDate = new DateTime(2018, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Belko Experiment",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 22,
                            CoverImage = "http://image.tmdb.org/t/p/w185/p70dq1YxabemdZDm5K6Q8G10wSn.jpg",
                            Description = "A mystery centered around the construction of the Great Wall of China.",
                            RelaseDate = new DateTime(2002, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Wall",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 23,
                            CoverImage = "http://image.tmdb.org/t/p/w185/BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
                            Description = "As a CODA (Child of Deaf Adults) Ruby is the only hearing person in her deaf family. When the family's fishing business is threatened, Ruby finds herself torn between pursuing her love of music and her fear of abandoning her parents.",
                            RelaseDate = new DateTime(2001, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CODA (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 24,
                            CoverImage = "http://image.tmdb.org/t/p/w185/tBUYDwiJVDcnjPneOitVetJk2Rt.jpg",
                            Description = "Mankind's earliest settlers on the Martian frontier do what they must to survive the cosmic elements and each other.",
                            RelaseDate = new DateTime(2001, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Settlers (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 25,
                            CoverImage = "http://image.tmdb.org/t/p/w185/2433Vt8xuDnAIDAJTNx6DEtf9Qb.jpg",
                            Description = "As his wedding day approaches, Ben heads to Miami with his soon-to-be brother-in-law James to bring down a drug dealer who's supplying the dealers of Atlanta with product.",
                            RelaseDate = new DateTime(2020, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ride Along 2",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 26,
                            CoverImage = "http://image.tmdb.org/t/p/w185/vOl6shtL0wknjaIs6JdKCpcHvg8.jpg",
                            Description = "A bride's wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game.",
                            RelaseDate = new DateTime(2000, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ready or Not (2019)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 27,
                            CoverImage = "http://image.tmdb.org/t/p/w185/jJ8TnHvWHaVadW5JJjGYsM07j9i.jpg",
                            Description = "Lightning McQueen sets out to prove to a new generation of racers that he's still the best race car in the world.",
                            RelaseDate = new DateTime(2020, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cars 3",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 28,
                            CoverImage = "http://image.tmdb.org/t/p/w185/xLPffWMhMj1l50ND3KchMjYoKmE.jpg",
                            Description = "Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis, and must step forward to lead his people and to be a hero to the world.",
                            RelaseDate = new DateTime(2012, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Aquaman",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 29,
                            CoverImage = "http://image.tmdb.org/t/p/w185/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
                            Description = "A group of space criminals must work together to stop the fanatical villain Ronan the Accuser from destroying the galaxy.",
                            RelaseDate = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 30,
                            CoverImage = "http://image.tmdb.org/t/p/w185/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
                            Description = "A young Chinese maiden disguises herself as a male warrior in order to save her father.",
                            RelaseDate = new DateTime(2009, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mulan (2020)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 31,
                            CoverImage = "http://image.tmdb.org/t/p/w185/lcyKve7nXRFgRyms9M1bndNkKOx.jpg",
                            Description = "A criminal mastermind unleashes a twisted form of justice in Spiral, the terrifying new chapter from the book of Saw.",
                            RelaseDate = new DateTime(2007, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spiral",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 32,
                            CoverImage = "http://image.tmdb.org/t/p/w185/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
                            Description = "The Bad Boys Mike Lowrey and Marcus Burnett are back together for one last ride in the highly anticipated Bad Boys for Life.",
                            RelaseDate = new DateTime(2015, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad Boys for Life (2020)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 33,
                            CoverImage = "http://image.tmdb.org/t/p/w185/4JeejGugONWpJkbnvL12hVoYEDa.jpg",
                            Description = "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the demigod to set things right.",
                            RelaseDate = new DateTime(2002, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moana",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 34,
                            CoverImage = "http://image.tmdb.org/t/p/w185/qwoGfcg6YUS55nUweKGujHE54Wy.jpg",
                            Description = "Captain Jack Sparrow searches for the trident of Poseidon.",
                            RelaseDate = new DateTime(2001, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pirates of the Caribbean: Dead Men Tell No Tales",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 35,
                            CoverImage = "http://image.tmdb.org/t/p/w185/if4hw3Ou5Sav9Em7WWHj66mnywp.jpg",
                            Description = "A fantasy re-telling of the medieval story of Sir Gawain and the Green Knight.",
                            RelaseDate = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Green Knight (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 36,
                            CoverImage = "http://image.tmdb.org/t/p/w185/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
                            Description = "Imprisoned, the mighty Thor finds himself in a lethal gladiatorial contest against the Hulk, his former ally. Thor must fight for survival and race against time to prevent the all-powerful Hela from destroying his home and the Asgardian civilization.",
                            RelaseDate = new DateTime(2003, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thor: Ragnarok",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 37,
                            CoverImage = "http://image.tmdb.org/t/p/w185/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
                            Description = "When Jane Foster is possessed by a great power, Thor must protect her from a new threat of old times: the Dark Elves.",
                            RelaseDate = new DateTime(2000, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thor: The Dark World",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 38,
                            CoverImage = "http://image.tmdb.org/t/p/w185/kwh9dYvZLn7yJ9nfU5sPj2h9O7l.jpg",
                            Description = "Follow-up film to the 2006 comedy centering on the real-life adventures of a fictional Kazakh television journalist named Borat.",
                            RelaseDate = new DateTime(2005, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Borat Subsequent Moviefilm (2020)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 39,
                            CoverImage = "http://image.tmdb.org/t/p/w185/mPrDJ7puYzPLG5kPM96iNszF2sM.jpg",
                            Description = "On Anna's birthday, Elsa and Kristoff are determined to give her the best celebration ever, but Elsa's icy powers may put more than just the party at risk.",
                            RelaseDate = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Frozen Fever",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 40,
                            CoverImage = "http://image.tmdb.org/t/p/w185/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
                            Description = "A former neurosurgeon embarks on a journey of healing only to be drawn into the world of the mystic arts.",
                            RelaseDate = new DateTime(2017, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Doctor Strange",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 41,
                            CoverImage = "http://image.tmdb.org/t/p/w185/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
                            Description = "T'Challa, after the death of his father, the King of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king.",
                            RelaseDate = new DateTime(2015, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Panther",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 42,
                            CoverImage = "http://image.tmdb.org/t/p/w185/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg",
                            Description = "Thomas and Bea are now married and living with Peter and his rabbit family. Bored of life in the garden, Peter goes to the big city, where he meets shady characters and ends up creating chaos for the whole family.",
                            RelaseDate = new DateTime(2018, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peter Rabbit 2: The Runaway (2021)",
                            TypeMovie = "Movies"
                        },
                        new
                        {
                            Id = 43,
                            CoverImage = "http://image.tmdb.org/t/p/w185/6GCOpT8QcNzup09TAMmvvk22LTR.jpg",
                            Description = "John Clark, a Navy SEAL, goes on a path to avenge his wife's murder only to find himself inside of a larger conspiracy.",
                            RelaseDate = new DateTime(2002, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tom Clancy's Without Remorse (2021)",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 44,
                            CoverImage = "http://image.tmdb.org/t/p/w185/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
                            Description = "Blacksmith Will Turner teams up with eccentric pirate \"Captain\" Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.",
                            RelaseDate = new DateTime(2011, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pirates of the Caribbean: The Curse of the Black Pearl",
                            TypeMovie = "TV Shows"
                        },
                        new
                        {
                            Id = 45,
                            CoverImage = "http://image.tmdb.org/t/p/w185/nztAld019tFjllW7VCJvPFiFkt8.jpg",
                            Description = "As a math savant uncooks the books for a new client, the Treasury Department closes in on his activities and the body count starts to rise.",
                            RelaseDate = new DateTime(2015, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Accountant",
                            TypeMovie = "Movies"
                        });
                });

            modelBuilder.Entity("MovieRating.API.Database.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Movie_Id")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Movie_Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("MovieRating.API.Database.ActorsMovies", b =>
                {
                    b.HasOne("MovieRating.API.Database.Actors", "Actors")
                        .WithMany()
                        .HasForeignKey("Actor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRating.API.Database.Movies", "Movies")
                        .WithMany()
                        .HasForeignKey("Movie_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actors");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieRating.API.Database.Rating", b =>
                {
                    b.HasOne("MovieRating.API.Database.Movies", "Movies")
                        .WithMany("MovieRatings")
                        .HasForeignKey("Movie_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieRating.API.Database.Movies", b =>
                {
                    b.Navigation("MovieRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
